# Generated by Django 3.2.3 on 2021-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
                ('imdb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metascores', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
