# Generated by Django 3.2.3 on 2021-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
