# Generated by Django 3.2.3 on 2021-06-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210609_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessnews',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='indianews',
            name='data',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worldnews',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
